# Generated by Django 4.2.7 on 2024-06-03 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_reservation_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='cancelled_by_user',
            field=models.BooleanField(default=False),
        ),
    ]
